service: ss-demo-teste
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: us-east-1
  memorySize: 128
  timeout: 10
  environment:
    INSTANCE_IDS: "ss-demo-teste"
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
          - "ec2:StartInstances"
          - "ec2:StopInstances"
          Resource: "*" 
          
plugins:
  - serverless-offline
  
functions:
  start:
    handler: src/handler.start
    name: ss-demo-teste-start
    events:
      - schedule: cron(00 12 ? * MON-FRI *) 
  stop:
    handler: src/handler.stop
    name: ss-demo-teste-stop
    events:
      - schedule: cron(00 22 ? * MON-FRI *)