name: Stop Lambda

on:
  workflow_dispatch:

jobs:
  stopping:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: npm
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY_ID }} 
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Lambda Invoke
        run: | 
           aws lambda invoke --function-name ss-demo-teste-stop test.log

